import React from 'react';

export const metadata = {
  title: 'AI Platform (Jin-Dev)',
  description: 'Generated by jin-dev',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
